name: goreleaser

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name'
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: "~1.13.1"
          args: release --skip-publish --skip-validate --release-notes=README.md
        env:
          GORELEASER_CURRENT_TAG: ${{inputs.tagName}}
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/**.tar.gz